### PR TITLE
Building the client

### PR DESCRIPTION
**Pull request by dannon**
Hi @xiaojay, thanks for the contribution in https://github.com/galaxyproject/galaxy/pull/2213.  When you work with the client code, you'll typically want to run 'make client' from the galaxy root directory to create all of the bundled artifacts, which I've done here.  Do you mind merging this, or alternately, doing it yourself to update the PR?

### CODE REVIEW

**Comment by xiaojay** [comment]
i don't mind. just merge it :)

**Comment by dannon** [comment]
@xiaojay If you click merge here on this PR, it'll automatically update everything.  Can you do that?  Then I can merge the other one.

**Comment by xiaojay** [comment]
ok, i merge your pr. do i need create new pr ?

2016-04-21 21:52 GMT+08:00 Dannon Baker notifications@github.com:

**Comment by dannon** [comment]
No, it automatically updates the previous PR since your branch here changed to include this commit.  Thanks again!

**Comment by xiaojay** [comment]
great. it's my pleasure

2016-04-21 21:57 GMT+08:00 Dannon Baker notifications@github.com:

**Pull request merged**
